cloudscape-design/actions

- .github/actions/build-package/action.yml
- .github/workflows/build-lint-test.yml
- .github/workflows/deploy.yml
- .github/workflows/dry-run.yml
- .github/workflows/release.yml
*Description of changes:* Updating the referenced branch of this repository in the workflows. I forgot to change those back to `main` after testing the original PR: https://github.com/cloudscape-design/actions/pull/1.
> chore: Update referenced branch

- .github/workflows/lint-pr.yml
*Description of changes:* Upgrade the last remaining action that uses outdated NodeJS.
> chore: Upgrade actions/github-script

- .github/workflows/release-gh-notes.yml
follow-up for this [PR](https://github.com/cloudscape-design/actions/pull/5)
> chore: read commit info from input in release step

- .github/actions/deploy-static/action.yml
- .github/workflows/deploy.yml
*Issue #, if available:* n/a
To be used in https://github.com/cloudscape-design/components/pull/1832
> Extract common deploy-static action

- .github/actions/unlock-dependencies/index.js
Updated the dependency removal script to support versions `2` and `3` of `package-lock.json`. 
> feat: Update unlock-dependencies script to work with v3 package-lock

- .github/actions/build-package/action.yml
Migrate packages from packing on repo root, to lib folder
> Enable publishing from lib folder

- .github/actions/build-package/action.yml
Corresponding https://github.com/cloudscape-design/documenter/pull/33
> chore: Publish documenter lib folder

- .github/actions/build-package/action.yml
- Corresponding https://github.com/cloudscape-design/jest-preset/pull/35
> chore: Publish jest-preset lib folder

- .github/workflows/dry-run.yml
> chore: Always build jest preset

- .github/actions/build-package/action.yml
After this PR is approved and merged this corresponding [PR](https://github.com/cloudscape-design/global-styles/pull/43) needs to be merged
A [dry-run PR](https://github.com/cloudscape-design/global-styles/pull/43) using the branch was done to check that everything works correctly
> chore: Publish global-styles lib folder

- .github/actions/build-package/action.yml
- Corresponding: https://github.com/cloudscape-design/collection-hooks/pull/65
> chore: Publish collection hooks lib folder

- .github/workflows/release.yml
Remove our usage of CodeArtifact in the release process by simplifying using CodeBuild.
> refactor: Replace CodeArtifact with CodeBuild

- .github/workflows/release.yml
The Importer project has been updated and has a new name
> chore: Update Importer build project name to v2

- .github/actions/build-package/action.yml
- .github/workflows/dry-run.yml
*Issue #, if available:* N/A
*Description of changes:* Add new chat-components repo to build workflows
> chore: Add chat-components to workflows

- .github/actions/build-package/action.yml
- .github/actions/upload-artifact/action.yml
This reverts commit 1ee6784e790d79734237c6f812d1f4c3754a126b.
> Revert "chore: Update actions/upload-artifact to v4"

- .github/workflows/dry-run.yml
To enable https://github.com/cloudscape-design/theming-core/pull/80
> chore: Add component-toolkit as dependency for theming-core

- .github/workflows/release.yml
Pass full repo name with owner.
> chore: Pass full repository name

- .github/workflows/release.yml
> chore: Revert env variable change

- .github/actions/build-package/action.yml
- .github/actions/download-artifact/action.yml
- .github/actions/upload-artifact/action.yml
This reverts commit 285df4c74937df78c5fc6f5827746455708b9baa.
> Revert "chore: Update to v4 of actions/download-artifact and actions/upload-artifact for all workflows except dry-run (#46)"

- .github/workflows/release.yml
Variable being passed was empty.
Use the correct variable.
> fix: Pass correct commit sha and message

- .github/actions/build-package/action.yml
- .github/workflows/dry-run.yml
Build tools will be added as a dependency for components, board components, chat components and code view
> chore: Update build and dry run for build-tools

- .github/workflows/dry-run.yml
Depends on https://github.com/cloudscape-design/components/pull/2760
> chore: Makes components dry run integ tests sharded

- .github/actions/build-repository/action.yml
Unexpected character in the action.
> chore: Remove unexpected character

- .github/workflows/dry-run.yml
> chore: Do not run unit tests for components

- .github/actions/build-repository/action.yml
Not sure how this got pushed with it
> chore: Change branch to main

- .github/workflows/dry-run.yml
Without the job specified the value would always be false and so always be skipped
Test against new change.
https://github.com/cloudscape-design/components/actions/runs/11722910329
> fix: Add missing job to needs list

- .github/actions/create-build-tree/generated/dependencies.json
- .github/actions/create-build-tree/generated/dependents.json
*Description of changes:* Added chat components and demos dependency as chat components are being used in chat demo.
> chore: Add chat components demos dependency

- .github/workflows/release.yml
Allow overriding the role to use as well as the build project.
> chore: Allow additional configuration in release workflow

- .github/actions/create-build-tree/index.js
The old condition seemed not to work as expected: https://github.com/cloudscape-design/components/actions/runs/15182094386/job/42693654294?pr=3531
> Change fallback condition for TREE_DIRECTION

- .github/actions/build-repository/action.yml
- .github/actions/create-build-tree/build-tree.js
- .github/actions/create-build-tree/index.js
- .github/workflows/dry-run.yml
- .github/workflows/release.yml
*Description of changes:* Re-working of #76 after further testing to ensure end artifacts are as expected
Testing: checked full import process, confirmed no unexpected diffs
> feat: Run full dependencies build as part of release

- .github/actions/build-repository/action.yml
- .github/workflows/dry-run.yml
> chore: Temporarily skip caching entirely for components build in dry-run

- .github/workflows/dry-run.yml
> chore: Match dependencies of buildComponents for all components test actions

- packages/apply-rulesets/src/__tests__/__snapshots__/apply-rulesets.test.ts.snap
- packages/apply-rulesets/src/constants.ts
- packages/apply-rulesets/src/create-or-update-ruleset.ts
Follow-up for #85 
Rolls out the rulesets to the components repo.
If it works for the components repo, we'll roll it out for the rest.
> chore: Adds more repos to the rulesets

- packages/apply-rulesets/src/__tests__/__snapshots__/apply-rulesets.test.ts.snap
- packages/apply-rulesets/src/apply-rulesets.ts
Missing configuration from #86 
Adds `components` to the basic ruleset.
> chore: Adds components to the basic ruleset

- packages/apply-rulesets/src/__tests__/__snapshots__/apply-rulesets.test.ts.snap
- packages/apply-rulesets/src/apply-rulesets.ts
- packages/apply-rulesets/src/constants.ts
* `test-utils` doesn't have code-cov
* Removing the `components` repo from checks
> chore: Removes components and test-utils from codecov

- packages/apply-rulesets/src/__tests__/__snapshots__/apply-rulesets.test.ts.snap
- packages/apply-rulesets/src/__tests__/apply-rulesets.test.ts
- packages/apply-rulesets/src/__tests__/create-or-update-ruleset.test.ts
- packages/apply-rulesets/src/apply-rulesets.ts
- packages/apply-rulesets/src/create-or-update-ruleset.ts
Adds repo-level rulesets applier as org-level rulesets don't support merge queue rules.
> chore: Adds repo-level rulesets

- packages/apply-rulesets/src/__tests__/__snapshots__/apply-rulesets.test.ts.snap
- packages/apply-rulesets/src/apply-rulesets.ts
- packages/apply-rulesets/src/constants.ts
*Issue #, if available:* Followup to #85 
Rolls out the rulesets to all of the existing repos.
> chore: Rolls out rulesets to all repos

- packages/apply-rulesets/src/__tests__/__snapshots__/apply-rulesets.test.ts.snap
- packages/apply-rulesets/src/constants.ts
It should be enabled on all of these
> enable merge queue rule on more repos
