cloudscape-design/actions

.github/actions/build-package/action.yml
.github/workflows/build-lint-test.yml
.github/workflows/release-gh-notes.yml
.github/workflows/release.yml

*Description of changes:* The newer version of `actions/checkout` uses NodeJS 20, so this is preferred.

chore: Upgrade to actions/checkout v4

---

.github/workflows/release-gh-notes.yml

Backward-compatible version of #5. This does no actual changes, but allows the new param in the job

release-gh-notes: add optional commit param

---

.github/workflows/build-lint-test.yml

*Issue #, if available:* Document `9GQ0AGFT9WdZ`
This change runs the `git-secrets` whenever a package is built. This helps to detect accidentally committed secrets.

chore: Run git-secrets as part of the build

---

.github/workflows/build-lint-test.yml

Upgrade the CodeQL actions to resolve warnings around NodeJS:
> CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
Dry-run: https://github.com/cloudscape-design/components/pull/1945

chore: Update CodeQL actions to v3

---

.github/actions/release-package/index.mjs

Remove code duplication. Currently we repeat this removal in several places:
https://github.com/cloudscape-design/board-components/blob/d5dd6dcc1629ae93134d934bf8ba648fb4b2d594/scripts/package-json.js#L15
https://github.com/cloudscape-design/code-view/blob/82b17cfb756d36582971c31b1c1fb91de7c910a8/scripts/package-json.js#L15
(other packages also do that but more obscure)
Tested in this run: https://github.com/cloudscape-design/board-components/actions/runs/7864470510
----

chore: remove scripts for all packages being published

---

.github/workflows/build-lint-test.yml
.github/workflows/dry-run.yml
.github/workflows/release.yml

Fixing this error: https://github.com/cloudscape-design/board-components/actions/runs/7864468231/job/21456319489#step:3:618
```
npm ERR! husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
```
This happens when running `npm pack` or `npm publish` for artifacts.

disable husky in CI environment

---

.github/actions/build-package/action.yml
.github/actions/patch-local-dependencies/utils.mjs

Test utils are recently refactored in this [commit](https://github.com/cloudscape-design/test-utils/commit/0b34fbbf8bee502962e4221965cf9465e7d8b085) where the artifacts now found in the lib folder. Lerna was also removed so we can also remove any special treatment there.

chore: Update build package logic for refactored test-utils

---

.github/actions/build-package/action.yml
.github/workflows/dry-run.yml

Changes browser-test-tools package to release out of the lib folder. The [browser test tools PR](https://github.com/cloudscape-design/browser-test-tools/pull/77) dry-run relies on this change to be merged before it can pass. The change has been tested against this branch and passed.

chore: Publish browser test tools lib folder

---

.github/workflows/dry-run.yml

This adds a job that will run the `test:motion` command that was added to the components package in https://github.com/cloudscape-design/components/pull/1823, so that motion tests are part of our GitHub workflows.
Ticket: `AWSUI-24275`
Animation testing strategy doc: `HViwARxNHC6F`
---

feat: Add motion test job to dry-run workflow

---

.github/actions/build-package/action.yml
.github/workflows/dry-run.yml

Code view package should be a first class of our build workflows
Tested in a manual workflow run: https://github.com/cloudscape-design/actions/actions/runs/8252362525
Dry-run in this PR is expected to fail, because it still uses the mainline workflow definitions

setup dry-run for code view component

---

.github/actions/build-package/action.yml
.github/workflows/build-lint-test.yml
.github/workflows/release.yml

After https://github.com/cloudscape-design/components/pull/2071 we should now use strict `npm install` in our builds to ensure that we are not throwing unexpected warnings anywhere to our customers
Created a dry-run in a separate branch:
https://github.com/cloudscape-design/actions/actions/runs/8341382193

remove force flag from installation workflows

---

.github/workflows/release-gh-notes.yml

This has been deprecated by GitHub actions. Change to recommended usage.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
*Testing:*
Not sure how to safely test this change. Looking for suggestions.

chore: Remove usage of set-output

---

.github/workflows/build-lint-test.yml

With the requirement of the CODECOV token PRs from forked repositories can no longer run this action. Apparently v4 allows tokenless contributions for this case.
---
https://github.com/codecov/codecov-action
v4 Release
v4 of the Codecov GitHub Action will use the [Codecov CLI](https://github.com/codecov/codecov-cli) to upload coverage reports to Codecov.
Breaking Changes
Tokenless uploading is unsupported. However, PRs made from forks to the upstream public repos will support tokenless (e.g. contributors to OS projects do not need the upstream repo's Codecov token)
Various arguments to the Action have been removed

chore: Upgrade codecov to v4

---

.github/actions/build-package/action.yml
.github/actions/upload-artifact/action.yml

v3 of upload-artifacts uses node 16 which is EOL while v4 uses node 20
Errors being shown in dry-runs:
"Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-node@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/."
v4 also brings [improvements](https://github.com/actions/upload-artifact?tab=readme-ov-file#improvements)
We also already use it in the [release](https://github.com/cloudscape-design/actions/blob/main/.github/workflows/release.yml#L42) workflow so it seems to work fine.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

chore: Update actions/upload-artifact to v4

---

.github/workflows/lint-pr.yml

Currently we only call `lint-pr` workflow on pull request events where PR payload is available in github action event, to support merge queue feature all required checks in PR must run on merge queue events where the PR payload is not available in merge group event.
This change allows to skip the PR title check when workflow is ran outside a PR context. 
example of a failing action https://github.com/cloudscape-design/global-styles/actions/runs/10222229620

chore: Don't fail lint-pr workflow outside pull_request trigger

---

.github/workflows/release.yml

Adds a AWSUI prefix to all variables create and used.
This makes it a bit clearer which variables are being explicitly passed to the build compared to those that are included as part of the event.
*Note*
All repositories will need to be updated to use the correct variable name.

chore: Standardise env variable and secret names with AWSUI_ prefix

---

.github/actions/build-package/action.yml
.github/actions/download-artifact/action.yml
.github/actions/upload-artifact/action.yml

The title says it all. Upgrading the dry-run workflow is not straight-forward because of this breaking change: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact.
Here's a test PR in the components repo to verify that this commit doesn't break anything: https://github.com/cloudscape-design/components/pull/2645

chore: Update to v4 of actions/download-artifact and actions/upload-artifact for all workflows except dry-run

---

.github/workflows/release.yml

Second attempt at this change: https://github.com/cloudscape-design/actions/commit/f2016f393421ed11f87b80e3f5a6d459f4f4da00
Tested via the actions this time. The needed change is to use the `full_name` which send the repository name with the owner. e.g. `@cloudscape-design/jest-prest`
Before:
```
AWSUI_GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }} -> jest-preset
```
After:
```
AWSUI_GITHUB_REPOSITORY_NAME: ${{ github.event.repository.full_name }} -> @cloudscape-design/jest-preset
```

chore: Update and standardise env variables with AWSUI_ prefix

---

.github/workflows/build-lint-test.yml

Because it is `true` by default, linter never runs in our PR builds

enable lint runs

---

.github/actions/build-repository/action.yml
.github/workflows/build-lint-test.yml

Tune `always()` conditions
1. Run "Upload additional artifacts" even if the tests fail. Needed to see allure report for the failed builds
2. Do not run Codecov if the tests failed, it is not needed
Tested in my experimental browser-test-tools PR: https://github.com/cloudscape-design/browser-test-tools/pull/134

always upload build artifacts

---

.github/actions/build-repository/action.yml
.github/workflows/build-lint-test.yml

Follow up for #71 
Turns out there are too many places where we reuse this action: https://github.com/search?q=org%3Acloudscape-design+actions%2Fbuild-repository&type=code
Updating all of them manually does not make sense. Let's change the default

update skip-lint default value

---

.github/workflows/release.yml

Allow configuring the codebuild project name via secrets. This allows changing of the role and project to point to the beta stack when needed.

chore: Allow configuring the codebuild project name via secrets

---

.github/workflows/release.yml

This reverts commit 63e23df0f6a0ec270e9f34e4759db8c4c709fa99 because it breaks consuming actions which do not have `actions: read` permissions ([example](https://github.com/cloudscape-design/components/actions/runs/14714641057)). For private repositories, we will have to duplicate some action code for the time being instead.

Revert "chore: Add actions:read permissions to Release workflow (#74)"

---

.github/workflows/dry-run.yml

Another small follow-up for: https://github.com/cloudscape-design/components/pull/3829
The "dry-run / Build components" name must not change for React 16 as we declare it as required in our rulesets.

fix: Fixes workflow name for components dry-run

---

.github/workflows/dry-run.yml

We defined shards flag as such: `--shard=${{ matrix.shard }}/${{ strategy.job-total }}`. However, the `strategy.job-total` is the total number of matrix combinations. It was equal to 4 when we only had shards, and it got increased to 8 when we added react version. The fix uses explicit shard values to address the immediate problem (we only run the half of integration tests now!) and avoid the same problem from happening in the future.

fix: Fixes test shards config
